### PR TITLE
audio route to speaker

### PR DESCRIPTION
**Pull request by jibon57**
In iPhone 6s audio was playing in ear speaker instated of loudspeaker. This will resolve the issue.

### CODE REVIEW

**Comment by jibon57** [comment]
@bradmartin Please review this :)

**Comment by bradmartin** [comment]
Hi @jibon57 thanks again for great PRs 😄 - can you confirm the demo works fine with the changes made here and nothing has broken? If so, then I'll merge, test the demo and publish. I don't know iOS native apis too well so even me reviewing it is not very helpful to me 😆 thanks again. Let me know and I'll get an update published later on. It's bed time here for me 💤

**Comment by jibon57** [comment]
@bradmartin I had checked the demo & it was working. I implemented it to my project also :-). I ain't expert neither Android nor iOS. I am just learning from you guys :). You can check it from your side too :)

**Comment by bradmartin** [comment]
I went ahead and bumped the major since this might change the expected outcome for users still on the 3.x.x version and hopefully it will reduce any issues being raised with the change. Thanks again @jibon57 👍

**Pull request merged**
